profile: 6666
message: liyong
server:
  port: 8881
eureka:
  client:
    service-url:
      defaultZone: http://${hyzs.common.eureka.host}:${hyzs.common.eureka.post}/eureka
  instance:
    prefer-ip-address: true

spring:
  kafka:
    bootstrap-servers: ${hyzs.common.kafka.host}:${hyzs.common.kafka.post}
