foo: SERVICE-HI

message: ${message}


eureka:
  client:
    service-url:
      defaultZone: http://${hyzs.common.eureka.host}:${hyzs.common.eureka.port}/eureka
  instance:
    prefer-ip-address: true