mess: hello sssss


hyzs:
  common:
    file:
      max-file-size: 10MB
      max-request-size: 10MB
    redis:
      host: localhost
      port: 6379
      password:
    log:
      level: DEBUG
    eureka:
      host: localhost
      port: 8761
    aouth:
      uri: 172.16.8.57:18882

# routes to serviceId
# routes to url
# zuul.routes.api-a-url.path=/userapi/**
# zuul.routes.api-a-url.url=http://localhost:8881/
#eureka.client.serviceUrl.defaultZone=http://localhost:8880/eureka/